# Generated by Django 3.0.5 on 2020-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_rater', '0003_venue_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
