# Generated by Django 3.0.5 on 2020-06-04 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_rater', '0005_venue_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroom',
            name='number',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(limit_value=0)),
        ),
    ]
