# Generated by Django 3.0.5 on 2020-06-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_rater', '0007_restroomreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='restroomreview',
            name='number',
        ),
        migrations.AlterField(
            model_name='restroomreview',
            name='baby',
            field=models.BooleanField(verbose_name='Changing Table'),
        ),
        migrations.AlterField(
            model_name='restroomreview',
            name='handicap',
            field=models.BooleanField(verbose_name='Handicap Accessible'),
        ),
        migrations.AlterField(
            model_name='restroomreview',
            name='needle',
            field=models.BooleanField(verbose_name='Sharps Container'),
        ),
        migrations.DeleteModel(
            name='Restroom',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
