# Generated by Django 3.0.5 on 2020-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_rater', '0002_auto_20200602_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='zip_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
