# Generated by Django 3.0.8 on 2020-07-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_rater', '0013_auto_20200716_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroomreview',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
